sudo: required
dist: trusty
language: c
compiler:
    - gcc
    - clang
os:
    - linux
    - osx

addons:
    apt:
        packages:
            - autoconf
            - automake
            - libtool
            - libnl-3-200
            - libnl-3-dev
            - libnl-route-3-200
            - libnl-route-3-dev
            - libibverbs-dev
            - librdmacm-dev
        sources:
            - ubuntu-toolchain-r-test

env:
    global:
        - AM_MAKEFLAGS="-j4"
        - CPPFLAGS="-I$HOME/bogus/include"
        - LDFLAGS="-I$HOME/bogus/lib"
        - LD_LIBRARY_PATH="$HOME/bogus/lib"
    matrix:
        - GCC_VERSION=default
        - GCC_VERSION=5

# Install dependencies for the verbs and usnic providers.  Open MPI is
# not currently using the verbs provider in Libfabric, so we might as
# well not build it.
before_install:
    - if [[ "GCC_VERSION" == "5" ]]; then COMPILERS="CC=gcc-5 CXX=g++-5 FC=gfortran-5"; fi
    - export CONFIGURE_ARGS="--prefix=$HOME/bogus $COMPILERS" DISTCHECK_CONFIGURE_FLAGS="$CONFIGURE_ARGS"
    - export DISTCHECK_CONFIGURE_FLAGS="$CONFIGURE_ARGS"
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone https://github.com/ofiwg/libfabric.git ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$GCC_VERSION" == "5" ]] ; then sudo apt-get --assume-yes install gcc-5 g++-5 gfortran-5; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd libfabric && ./autogen.sh && ./configure --prefix=$HOME/bogus --enable-usnic --disable-verbs $COMPILERS && make install && cd .. ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$GCC_VERSION" == "5" ]] ; then brew update; brew unlink gcc ; brew install gcc; fi

install:
    - m4 --version
    - autoconf --version
    - automake --version
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then libtool --version; else glibtool --version; fi
    - ./autogen.pl
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC" == "gcc" ]]; then ./configure $CONFIGURE_ARGS --with-libfabric=$HOME/bogus --with-usnic --with-verbs; else ./configure $CONFIGURE_ARGS; fi
    - make -k

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC" == "gcc" ]]; then make distcheck; else make check; fi

matrix:
  exclude:
    - env: GCC_VERSION=5
      compiler: clang
